name: Deploy to GitHub Pages from src/

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload jacoco/ to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./jacoco

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
